const roles={admin:'Administrator',ktt:'KTT / PTL',inspector:'Inspector / Pengawas',pic:'PIC Area',verifier:'Verifier HSE',viewer:'Viewer / Auditor'};
const permissions={admin:['create','execute','request_close','verify','close_finding','close_inspection','reopen'],ktt:['create','verify','close_finding','close_inspection','reopen'],inspector:['create','execute','request_close','close_report'],pic:['request_close'],verifier:['verify','close_finding','close_report'],viewer:[]};
const inspections=[
{id:'INS-2026-071',title:'Jalan angkut Pit Timur',area:'Mining',risk:'Ekstrem',inspector:'Supervisor Produksi',date:'2026-07-23',reportDue:'2026-07-24',closingDue:'2026-07-26',status:'Menunggu Closing',progress:86,findings:'2/3 closed'},
{id:'INS-2026-072',title:'Workshop alat berat',area:'Plant',risk:'Tinggi',inspector:'Andi Saputra',date:'2026-07-24',reportDue:'2026-07-24',closingDue:'2026-07-31',status:'Berlangsung',progress:67,findings:'1 temuan'},
{id:'INS-2026-073',title:'Stockpile & crusher',area:'CHPP',risk:'Tinggi',inspector:'CHPP Supervisor',date:'2026-07-25',reportDue:'2026-07-26',closingDue:'2026-08-02',status:'Direncanakan',progress:0,findings:'—'},
{id:'INS-2026-074',title:'Gudang bahan peledak',area:'Blasting',risk:'Ekstrem',inspector:'Juru Ledak',date:'2026-07-28',reportDue:'2026-07-28',closingDue:'2026-07-30',status:'Direncanakan',progress:0,findings:'—'},
{id:'INS-2026-068',title:'Fuel station',area:'Plant',risk:'Ekstrem',inspector:'Plant Inspector',date:'2026-07-18',reportDue:'2026-07-18',closingDue:'2026-07-20',status:'Closing Terlambat',progress:78,findings:'1/2 closed'}];
const findings=[
{id:'F-018',title:'Bundwall tangki BBM rusak',inspection:'INS-2026-068',area:'Fuel Station',risk:'Ekstrem',pic:'Plant Manager',due:'2026-07-20',status:'action',progress:70},
{id:'F-021',title:'Rambu tikungan tidak terlihat',inspection:'INS-2026-071',area:'Hauling Road KM 4',risk:'Tinggi',pic:'Road Maintenance',due:'2026-07-22',status:'open',progress:20},
{id:'F-023',title:'Guard conveyor longgar',inspection:'INS-2026-073',area:'Crusher 01',risk:'Tinggi',pic:'CHPP Maintenance',due:'2026-07-25',status:'action',progress:55},
{id:'F-015',title:'APAR melewati jadwal inspeksi',inspection:'INS-2026-066',area:'Workshop',risk:'Sedang',pic:'HSE Plant',due:'2026-07-23',status:'verification',progress:100},
{id:'F-016',title:'Housekeeping area welding',inspection:'INS-2026-066',area:'Workshop',risk:'Sedang',pic:'Workshop Supervisor',due:'2026-07-24',status:'verification',progress:100},
{id:'F-012',title:'Drainase jalan tertutup material',inspection:'INS-2026-063',area:'Pit Barat',risk:'Tinggi',pic:'Mine Services',due:'2026-07-18',status:'closed',progress:100},
{id:'F-009',title:'Lampu penerangan tidak berfungsi',inspection:'INS-2026-059',area:'ROM Stockpile',risk:'Sedang',pic:'Electrical',due:'2026-07-16',status:'closed',progress:100},
{id:'F-024',title:'Kabel ekstensi melintasi akses',inspection:'INS-2026-072',area:'Workshop',risk:'Tinggi',pic:'Plant Maintenance',due:'2026-07-26',status:'open',progress:0}];
const checkItems=[['Kondisi lantai dan akses kerja','Bebas tumpahan, lubang, dan penghalang','ok'],['Pengamanan energi berbahaya (LOTO)','Prosedur dan perangkat tersedia serta digunakan','ok'],['Peralatan angkat dan aksesorinya','Identitas, SWL, inspeksi, dan kondisi fisik','bad'],['Pelindung mesin dan bagian bergerak','Guard terpasang dan tidak dimodifikasi','ok'],['Penyimpanan bahan mudah terbakar','Terpisah, berlabel, ventilasi memadai','ok'],['APAR dan jalur evakuasi','Mudah diakses, berlaku, dan ditandai',''],['Housekeeping area kerja','Material dan peralatan tertata',''],['PPE dan kepatuhan pekerja','Sesuai bahaya pekerjaan','']];
let currentRole=localStorage.getItem('jpc-role')||'admin';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const fmtDate=s=>new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${s}T00:00:00`));
const day=s=>new Date(`${s}T00:00:00`).getDate();
const month=s=>new Intl.DateTimeFormat('id-ID',{month:'short'}).format(new Date(`${s}T00:00:00`)).toUpperCase();
const riskClass=r=>r==='Ekstrem'?'red':r==='Tinggi'?'orange':r==='Sedang'?'blue':'green';
const statusClass=s=>s.includes('Terlambat')?'red':s.includes('Closed')?'green':s.includes('Berlangsung')?'blue':s.includes('Closing')?'orange':'gray';
const can=action=>permissions[currentRole].includes(action);
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const labels={dashboard:['Dashboard Inspeksi','Kendali jadwal, temuan, tindak lanjut, dan closing'],schedule:['Jadwal Inspeksi','Pelaksanaan, laporan, dan target closing'],execution:['Pelaksanaan Inspeksi','Checklist dan bukti pemeriksaan lapangan'],findings:['Temuan & Closing','Tindak lanjut, bukti, verifikasi, dan penutupan'],verification:['Verifikasi Closing','Pemeriksaan independen sebelum penutupan'],checklists:['Checklist & Standar','Template terkendali dan dasar pemeriksaan'],objects:['Objek & Risiko','Register objek dan frekuensi berbasis risiko'],reports:['Laporan & Audit Trail','Dokumentasi kepatuhan dan jejak perubahan'],settings:['Pengaturan','Peran, SLA, notifikasi, dan integrasi']};$('#pageTitle').textContent=labels[id][0];$('#pageSubtitle').textContent=labels[id][1];$('#sidebar').classList.remove('open');scrollTo(0,0)}
function inspectionCell(i){return `<div class="inspection-cell"><div class="date-box"><b>${day(i.date)}</b><small>${month(i.date)}</small></div><div><strong>${i.title}</strong><small>${i.id} · ${i.area}</small></div></div>`}
function renderInspections(){const dash=inspections.slice(0,5).map(i=>`<tr><td>${inspectionCell(i)}</td><td>${fmtDate(i.date)}</td><td><div class="due-cell"><strong class="${i.status.includes('Terlambat')?'danger':''}">${fmtDate(i.closingDue)}</strong><small>${i.findings}</small></div></td><td><div class="progress-compact"><div><span style="width:${i.progress}%"></span></div><small>${i.progress}%</small></div></td><td><span class="badge ${statusClass(i.status)}">${i.status}</span></td><td><button class="row-action" data-inspection="${i.id}">Detail</button></td></tr>`).join('');$('#dashboardInspectionRows').innerHTML=dash;$('#scheduleRows').innerHTML=inspections.map(i=>`<tr><td>${inspectionCell(i)}</td><td><span class="badge ${riskClass(i.risk)}">${i.risk}</span><small style="display:block;color:var(--muted);margin-top:4px">${i.area}</small></td><td>${i.inspector}</td><td>${fmtDate(i.date)}</td><td>${fmtDate(i.reportDue)}</td><td><b class="${i.status.includes('Terlambat')?'danger':''}">${fmtDate(i.closingDue)}</b></td><td><span class="badge ${statusClass(i.status)}">${i.status}</span></td><td><button class="row-action" data-inspection="${i.id}">Buka</button></td></tr>`).join('')}
function renderPriorities(){$('#priorityFindings').innerHTML=findings.filter(f=>f.risk==='Ekstrem'||f.risk==='Tinggi').slice(0,4).map(f=>`<div class="priority-item"><strong>${f.title}</strong><span class="badge ${riskClass(f.risk)}">${f.risk}</span><p>${f.area} · PIC: ${f.pic} · target ${fmtDate(f.due)}</p><button data-finding="${f.id}">Buka temuan →</button></div>`).join('')}
function renderBoard(){const columns=[['open','Temuan Baru'],['action','Tindak Lanjut'],['verification','Menunggu Verifikasi'],['closed','Closed']];$('#findingBoard').innerHTML=columns.map(([key,label])=>{const list=findings.filter(f=>f.status===key);return `<section class="kanban-column"><div class="kanban-head"><strong>${label}</strong><span>${list.length}</span></div>${list.map(f=>`<article class="finding-card"><div><span class="badge ${riskClass(f.risk)}">${f.risk}</span><small>${f.id}</small></div><h3>${f.title}</h3><p>${f.area}<br>PIC: ${f.pic}</p><div class="finding-meta"><span>Target ${fmtDate(f.due)}</span><b>${f.progress}%</b></div><button data-finding="${f.id}">Lihat & proses →</button></article>`).join('')}</section>`}).join('')}
function renderVerification(){const list=findings.filter(f=>f.status==='verification'||f.id==='F-018');$('#verificationQueue').innerHTML=list.map(f=>`<article class="verification-item"><div><span class="badge ${riskClass(f.risk)}">${f.risk}</span><h3>${f.title}</h3><p>${f.id} · ${f.area} · diajukan oleh ${f.pic}</p><div class="evidence"><span>📷 Foto sebelum</span><span>📷 Foto sesudah</span><span>▤ Catatan tindakan</span></div></div><div class="verification-actions"><button class="btn secondary" data-reject="${f.id}">Tolak</button><button class="btn primary" data-verify="${f.id}">Verifikasi & close</button></div></article>`).join('')}
function renderChecklist(){$('#checklistItems').innerHTML=checkItems.map((c,n)=>`<div class="check-item"><span class="check-number">${n+1}</span><div><strong>${c[0]}</strong><small>${c[1]}</small></div><div class="check-options"><button class="${c[2]==='ok'?'selected ok':''}" data-check="${n}" data-value="ok">OK</button><button class="${c[2]==='bad'?'selected bad':''}" data-check="${n}" data-value="bad">TS</button><button data-check="${n}" data-value="na">N/A</button></div></div>`).join('')}
function bindDynamic(){document.addEventListener('click',e=>{const f=e.target.closest('[data-finding]');if(f)openFinding(f.dataset.finding);const i=e.target.closest('[data-inspection]');if(i){toast(`Membuka ${i.dataset.inspection} (demo)`)}const check=e.target.closest('[data-check]');if(check){const group=check.parentElement;$$('button',group).forEach(b=>b.className='');check.className=check.dataset.value==='ok'?'selected ok':check.dataset.value==='bad'?'selected bad':'selected';if(check.dataset.value==='bad')toast('Butir tidak sesuai — buat temuan dan tindakan segera.')}const verify=e.target.closest('[data-verify]');if(verify){if(!can('verify'))return toast('Peran ini tidak berwenang memverifikasi closing.');const item=findings.find(x=>x.id===verify.dataset.verify);item.status='closed';renderAll();toast(`${item.id} terverifikasi dan ditutup.`)}const reject=e.target.closest('[data-reject]');if(reject){if(!can('verify'))return toast('Peran ini tidak berwenang menolak verifikasi.');const item=findings.find(x=>x.id===reject.dataset.reject);item.status='action';renderAll();toast(`${item.id} dikembalikan kepada PIC untuk perbaikan.`)}})}
function openFinding(id){const f=findings.find(x=>x.id===id);if(!f)return;$('#drawerFindingId').textContent=f.id;$('#drawerFindingTitle').textContent=f.title;$('#drawerArea').textContent=f.area;$('#drawerPic').textContent=f.pic;$('#drawerDue').textContent=fmtDate(f.due);$('#drawerRisk').textContent=f.risk;$('#drawerRisk').className=`badge ${riskClass(f.risk)}`;const labels={open:'Temuan baru',action:'Tindak lanjut',verification:'Menunggu verifikasi',closed:'Closed'};$('#drawerStatus').textContent=labels[f.status];$('#drawerActions').innerHTML=drawerButtons(f);$('#findingDrawer').classList.add('open')}
function drawerButtons(f){if(f.status==='closed')return can('reopen')?`<button class="btn secondary" id="reopenBtn">Buka kembali</button>`:`<button class="btn secondary" disabled>Temuan telah ditutup</button>`;if(f.status==='verification')return can('verify')?`<button class="btn secondary" id="rejectBtn">Tolak</button><button class="btn primary" id="verifyBtn">Verifikasi & close</button>`:`<button class="btn secondary" disabled>Menunggu verifier</button>`;return can('request_close')?`<button class="btn secondary" id="saveProgressBtn">Simpan progress</button><button class="btn primary" id="requestCloseBtn">Ajukan closing</button>`:`<button class="btn secondary" disabled>Hanya PIC/Inspector dapat mengajukan closing</button>`}
function currentDrawerFinding(){return findings.find(f=>f.id===$('#drawerFindingId').textContent)}
function updateRole(){localStorage.setItem('jpc-role',currentRole);$('#sidebarRole').textContent=roles[currentRole];$('#roleSelect').value=currentRole;$('#newInspectionBtn').hidden=!can('create');$('#newInspectionBtn2').hidden=!can('create');$$('[data-verify],[data-reject]').forEach(b=>b.disabled=!can('verify'));const f=currentDrawerFinding();if(f)$('#drawerActions').innerHTML=drawerButtons(f);toast(`Peran aktif: ${roles[currentRole]}`)}
function openModal(){$('#inspectionModal').classList.add('open');setTimeout(()=>$('#inspectionForm input').focus(),50)}function closeModal(){$('#inspectionModal').classList.remove('open')}
function renderAll(){renderInspections();renderPriorities();renderBoard();renderVerification();renderChecklist()}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.jump)));$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#roleSelect').addEventListener('change',e=>{currentRole=e.target.value;updateRole()});['#newInspectionBtn','#newInspectionBtn2'].forEach(s=>$(s)?.addEventListener('click',openModal));$$('.close-modal').forEach(b=>b.addEventListener('click',closeModal));$('#inspectionModal').addEventListener('click',e=>{if(e.target.id==='inspectionModal')closeModal()});$('#inspectionForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const next={id:`INS-2026-${String(75+inspections.length).padStart(3,'0')}`,title:fd.get('title'),area:fd.get('area'),risk:fd.get('risk'),inspector:fd.get('inspector'),date:fd.get('inspectionDate'),reportDue:fd.get('reportDue'),closingDue:fd.get('closingDue'),status:'Direncanakan',progress:0,findings:'—'};inspections.unshift(next);renderInspections();closeModal();e.currentTarget.reset();toast(`${next.id} berhasil dibuat dengan jadwal closing.`)});$('#closeDrawer').addEventListener('click',()=>$('#findingDrawer').classList.remove('open'));$('#findingDrawer').addEventListener('click',e=>{if(e.target.id==='findingDrawer')e.currentTarget.classList.remove('open')});$('#drawerActions').addEventListener('click',e=>{const f=currentDrawerFinding();if(e.target.id==='saveProgressBtn')toast('Progress dan bukti disimpan.');if(e.target.id==='requestCloseBtn'){if(!$('#closureNote').value.trim())return toast('Isi catatan tindakan sebelum mengajukan closing.');f.status='verification';renderAll();openFinding(f.id);toast('Closing diajukan kepada verifier.');}if(e.target.id==='verifyBtn'){f.status='closed';renderAll();openFinding(f.id);toast('Bukti efektif. Temuan telah ditutup.');}if(e.target.id==='rejectBtn'){f.status='action';renderAll();openFinding(f.id);toast('Closing ditolak dan dikembalikan ke PIC.');}if(e.target.id==='reopenBtn'){f.status='action';renderAll();openFinding(f.id);toast('Temuan dibuka kembali dan audit trail dicatat.')}});$('#exportBtn').addEventListener('click',()=>toast('Ekspor laporan sedang disiapkan (demo).'));$('#criticalBtn').addEventListener('click',()=>toast('Bahaya kritis dicatat dan notifikasi KTT/PTL dibuat.'));$('#submitReportBtn').addEventListener('click',()=>toast('Laporan dikirim untuk review dan jadwal closing dimulai.'));$('#newFindingBtn').addEventListener('click',()=>toast('Form temuan baru akan dibuka (demo).'));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();$('#findingDrawer').classList.remove('open')}});
renderAll();bindDynamic();$('#roleSelect').value=currentRole;$('#sidebarRole').textContent=roles[currentRole];
fetch('/api/config').then(r=>r.json()).then(c=>{if(c.supabaseConfigured){const el=$('.integration-status');if(el){el.textContent='Supabase siap dikonfigurasi';el.style.color='var(--blue)';el.style.background='var(--blue-soft)'}}}).catch(()=>{});
